### ISSUE TITLE
Refuses to be enabled on the Normal 4.0 version of blender

### ISSUE THREAD

**Issue by AlphaCabb** [NevilArt/BsMax#43]
**Here's the error message i get when i try to enable it**

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\jeuxv\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BsMax-master\__init__.py", line 580, in register
    register_primitives(preferences)
  File "C:\Users\jeuxv\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BsMax-master\primitive\__init__.py", line 67, in register_primitives
    register_update()
  File "C:\Users\jeuxv\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BsMax-master\primitive\update.py", line 648, in register_update
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'PrimitiveData'

https://github.com/user-attachments/assets/696fcc90-3275-469b-b444-3d99e378acc4

**the version of blender i use is (4.0 Stable version) because the most recent versions don't have the updated addons i use**

- Blender 4.0 Stable

**It installs itself without any issues but everytime i click to enable it i get the error message stated above and i'm kind of in a pickle because of it since i need this addon for an entry exam at a 3d modeling school **

**please help me fast with this, thank you in advance**

**Comment by NevilArt** [comment]
Hi, Sorry for late respond.
I just test the current BsMax in github with Blender 4.0.1 and in windows 10 and it is work whit out issue.
Can you reset the blender to factory mode (File/ Defaults/ Load factory setting) and test again?
Please let me know if it works or not and I`ll try to fix it soon as possible.

**Comment by AlphaCabb** [comment]
okay i seem to have found the problem, it seems that your addon is Incompatible with ShapeKeys+. but when i reset blender to factory settings and don't re-enable Shapekeys+ bam it works

**Comment by NevilArt** [comment]
Good, at least I know have to work on compatibility with "Shape Key+".
Thank you for useful information.

**Comment by NevilArt** [comment]
Sole for very long delay, finlay I get a bit free time to work on this issue and fix it.
The Developer of shape key plus has removed "bpy.types.DATA_PT_shape_keys" panel that I was put my stuff on that.
I just add a line to ignore if this panel missing,
I will upload fix soon
